category: dev-python
conflicts: []
description: Library to export django metrics for prometheus
id: 0
license: Apache-1.0
name: django-prometheus
requires:
  
  category: dev-python
  id: 0
  name: prometheus_client
  
  version: 0.0.21
uri:
- mirror://pypi/d/django-prometheus/django-prometheus-1.0.15.tar.gz
version: 1.0.15
