category: app-metrics
description: Prometheus monitoring system and time series database
license: Apache-2.0 BSD BSD-2 ISC MIT MPL-2.0
name: prometheus
uri:
- https://github.com/prometheus/prometheus/archive/v2.13.1.tar.gz -> prometheus-2.13.1.tar.gz
use_flags:
- ""
version: 2.13.1
