category: dev-python
conflicts: []
description: Library to export django metrics for prometheus
id: 0
license: Apache-1.0
name: django-prometheus
requires:
  
  category: dev-python
  id: 0
  name: prometheus_client
  
  version: "0.7"
uri:
- mirror://pypi/d/django-prometheus/django-prometheus-1.1.0.tar.gz
version: 1.1.0
