category: dev-python
conflicts: []
description: Provides HTTP request metrics to export into Prometheus
license: MIT
name: prometheus_flask_exporter
requires:
- 
  category: dev-python
  description: ""
  license: ""
  name: flask
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: prometheus_client
  
  version: ""
uri:
- https://github.com/rycus86/prometheus_flask_exporter/archive/0.4.1.tar.gz -> prometheus_flask_exporter-0.4.1.tar.gz
use_flags:
- test
version: 0.4.1
