category: app-emulation
conflicts: []
description: Cloud instance initialisation magic
id: 0
license: GPL-3
name: cloud-init
requires:
  category: dev-python
  id: 0
  name: oauthlib
  version: ""
  category: dev-python
  id: 0
  name: pyyaml
  version: ""
  category: dev-python
  id: 0
  name: jsonpatch
  version: ""
  category: sys-fs
  id: 0
  name: growpart
  version: ""
  category: dev-python
  id: 0
  name: six
  version: ""
  category: net-analyzer
  id: 0
  name: macchanger
  version: ""
  category: sys-apps
  id: 0
  name: iproute2
  version: ""
  category: dev-python
  id: 0
  name: jinja
  version: ""
  category: dev-python
  id: 0
  name: pyserial
  version: ""
  category: dev-python
  id: 0
  name: configobj
  version: 5.0.2
  category: dev-python
  id: 0
  name: requests
  version: ""
  category: dev-python
  id: 0
  name: jsonschema
  version: ""
  category: virtual
  id: 0
  name: logger
  version: ""
uri:
- https://launchpad.net/cloud-init/trunk/19.4/+download/cloud-init-19.4.tar.gz
use_flags:
- test
version: "19.4"
