category: app-emulation
conflicts: []
description: Multi-container orchestration for Docker
license: Apache-2.0
name: docker-compose
requires:
- 
  category: dev-python
  description: ""
  license: ""
  name: docker-py
  
  version: 3.7.0
- 
  category: dev-python
  description: ""
  license: ""
  name: dockerpty
  
  version: 0.4.1
- 
  category: dev-python
  description: ""
  license: ""
  name: jsonschema
  
  version: 2.5.1
- 
  category: dev-python
  description: ""
  license: ""
  name: PySocks
  
  version: 1.6.0
- 
  category: dev-python
  description: ""
  license: ""
  name: pyyaml
  
  version: "3.10"
- 
  category: dev-python
  description: ""
  license: ""
  name: websocket-client
  
  version: 0.32.0
- 
  category: dev-python
  description: ""
  license: ""
  name: setuptools
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: cached-property
  
  version: 1.2.0
- 
  category: dev-python
  description: ""
  license: ""
  name: docopt
  
  version: 0.6.1
- 
  category: dev-python
  description: ""
  license: ""
  name: paramiko
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: requests
  
  version: 2.18.1
- 
  category: dev-python
  description: ""
  license: ""
  name: six
  
  version: 1.3.0
- 
  category: dev-python
  description: ""
  license: ""
  name: texttable
  
  version: 0.9.0
uri:
- https://github.com/docker/compose/archive/1.24.0.tar.gz -> docker-compose-1.24.0.tar.gz
use_flags:
- test
version: 1.24.0
